services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finesse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/finesse
      - SQLITE_DB=postgresql+psycopg2://postgres:postgres@db:5432/finesse
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  pgdata:
